# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Kv9rR3eJA098eEUCgWfBN6i5k6V63mz

IMPORT LIBRARIES
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

""" LOAD DATASET"""

df = pd.read_csv("/content/creditcard.csv")

"""DATA CLEANING"""

print(df.isnull().sum())
df = df.drop_duplicates()

""" DESCRIPTIVE STATISTICS"""

print(df.describe())

print("\nAverage Amount:", df['Amount'].mean())
print("\nFraud Count:\n", df['Class'].value_counts())

"""RISK ANALYSIS"""

def risk(x):
    if x < 100:
        return "Low Risk"
    elif x < 1000:
        return "Medium Risk"
    else:
        return "High Risk"

df['Risk_Level'] = df['Amount'].apply(risk)

"""VISUALIZATIONS

Fraud Distribution
"""

sns.countplot(x='Class', data=df)
plt.title("Fraud vs Normal")
plt.show()

"""Amount Distribution

"""

plt.hist(df['Amount'], bins=50)
plt.title("Transaction Amount")
plt.show()

"""Fraud vs Amount

"""

sns.boxplot(x='Class', y='Amount', data=df)
plt.title("Fraud vs Amount")
plt.show()

"""Time vs Amount

"""

plt.scatter(df['Time'], df['Amount'])
plt.title("Time vs Amount")
plt.xlabel("Time")
plt.ylabel("Amount")
plt.show()

"""Correlation Heatmap

"""

plt.figure(figsize=(10,8))
sns.heatmap(df.select_dtypes(include='number').corr(), cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""HANDLE MISSING VALUES

"""

df = df.fillna(df.mean(numeric_only=True))

""" LINEAR REGRESSION

"""

X = df[['Time', 'Amount']]
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

"""MODEL EVALUATION


"""

print("\nR2 Score:", r2_score(y_test, y_pred))

"""INTERACTIVE DASHBOARD

Fraud Distribution Dashboard
"""

fig1 = px.pie(df, names='Class',
              title='Fraud Distribution')
fig1.show()

"""Amount Trend Dashboard

"""

fig2 = px.histogram(df, x='Amount',
                    title='Transaction Amount Distribution')
fig2.show()

"""Scatter Dashboard

"""

fig3 = px.scatter(df, x='Time', y='Amount',
                  color='Class',
                  title='Fraud Comparison')
fig3.show()

"""FINAL INSIGHTS

"""

print("\nInsights:")
print("• Fraud transactions are very less")
print("• High amount transactions may be risky")
print("• Heatmap shows important feature relationships")
print("• Dashboard helps understand fraud patterns")

